### ISSUE TITLE
.jar fails to connect to Gatling.io

### ISSUE THREAD

**Issue by cccs-kevin** [OPSWAT/metadefender-gatling-test#3]
Hi there,

I'm having some difficulty using this script.

My MD Core is hosted at <my-ip> and is not accessible from the Internet. I tried replacing the ApiKey that is supposed to be for MetaDefender Cloud with the one associated with my MD Core (<my-key>) and that didn't work. I'm running this script from a machine that has Internet access and private network access to the network that the MD Core is hosted.

My target/config.ini is as follows:
```
[general]
BaseUrl=http://<my-ip>:<my-port>/v4/file
;constant concurrent users
ConstantUsers=5
;time to run, (s)
TestDuration=10
;time before full filling, (s)
ScanWorkflow=multiscan
;dataset folder
LocalPath=C:\OPSWAT\data
;sleep time between each polling scan result (ms)
PollingIntervals=500
;OPSWAT MetaDefender Cloud apikey
ApiKey=<my-key>
;waiting time between push file and start to polling (ms)
WaitBeforePolling=1000
```

Based on the attached logs, it also looks like the script is unable to reach https://gatling.io.

[logs.txt](https://github.com/OPSWAT/metadefender-gatling-test/files/6064017/logs.txt)

Any ideas on how to resolve this?

**Comment by cccs-kevin** [comment]
So I think this ^ was related to my environment and how my env handles SSL.

**Comment by cccs-kevin** [comment]
Additional logs from a different machine (Win10x64) in the same Virtual Network as the MD Core VM.

[logs2.txt](https://github.com/OPSWAT/metadefender-gatling-test/files/6064402/logs2.txt)

Similar situation when run in Ubuntu 18.04 LTS x64...

**Comment by horvvpeter** [comment]
Hello @cccs-kevin !

If you are trying to run the tool on local MD Core setup please check/try the followings:

- **BaseUrl** should be http://\<my-ip\>:\<my-port\>/file (without **/v4/** in the path)
- **ScanWorkflow** should be an existing workflow in your MD Core setup. For example '_File process_' if you have the default workflows. Please check: [online documentation](https://onlinehelp.opswat.com/corev4/3.6.4._Workflow_rule_configuration.html)
- Make sure that the directory set in **LocalPath** exists on the computer where you are running the tool (C:\OPSWAT\data in your example config). It should have at least one file in it.
- Make sure the **ApiKey** is a valid existing apikey in your MD Core setup and is assigned to a user who can use the selected workflow. Please check: [online documentation](https://onlinehelp.opswat.com/corev4/3.3.1._Users_and_groups.html)

**Comment by cccs-kevin** [comment]
Hey @horvvpeter thanks for the quick reply :)

I'm also running the .jar with Java 11 as suggested by https://github.com/OPSWAT/metadefender-gatling-test/issues/4#issuecomment-788858849

So I made the changes you suggested and the error I'm receiving is the same I believe: 
[logs5.txt](https://github.com/OPSWAT/metadefender-gatling-test/files/6068958/logs5.txt)

**Comment by horvvpeter** [comment]
Hi @cccs-kevin !

I can see http://\<md-ip\>:\<md-port\>/file in the logs. Is that how you have in the config.ini or you modified the logfile before uploading it? If that is how you have it in the ini please put in a real address, like http://localhost:8008/file

**Comment by cccs-kevin** [comment]
@horvvpeter  haha ya I modified the log file before uploading it :)

**Comment by horvvpeter** [comment]
@cccs-kevin In that case I suspect a problem with LocalPath, at least I get the same type of errors when I set a LocalPath which doesn't exist

**Comment by cccs-kevin** [comment]
@horvvpeter I was using a LocalPath for a specific file that existed, and when I changed the LocalPath to the directory that contained that specific file, the program worked! Thanks for your help. Closing issue.

Although this log about not being able to reach https://gatling.io still occurs:
```
08:49:43.498 [main] DEBUG io.gatling.http.engine.HttpEngine - Couldn't execute warm up request https://gatling.io
io.gatling.http.client.impl.RequestTimeoutException: Request timeout to gatling.io/34.77.242.251:443 after 1000 ms
08:49:43.502 [main] INFO io.gatling.http.engine.HttpEngine - Warm up done
08:49:43.539 [main] DEBUG io.gatling.http.cache.HttpCaches - HTTP/2 disabled
Simulation ScanSimulation started...
```
