### ISSUE TITLE
Failed run due to missing libraries

### ISSUE THREAD

**Issue by cccs-kevin** [OPSWAT/metadefender-gatling-test#4]
Tried to run this in Windows 10x64 VM that was in the same network as the MD Core VM. 

```
> java -version
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) Client VM (build 25.281-b09, mixed mode)
```

Got the following logs. Looks like there is an issue with missing libraries.
`Caused by: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_windows_x86_32, netty_tcnative_x86_32, netty_tcnative]`

Any idea how to resolve?

[logs.txt](https://github.com/OPSWAT/metadefender-gatling-test/files/6064335/logs.txt)

**Comment by petya2164** [comment]
@cccs-kevin Can you please try to run the tool with Java 11? 
Unfortunately, Java 8 is not supported.

**Comment by cccs-kevin** [comment]
Hey @petya2164 thanks for the quick reply :)

I'm running the .jar with Java 11 now 
```
java -version
java version "11.0.7" 2020-04-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)
```
And I'm still getting the same ERROR messages when I run the .jar:
[logs5.txt](https://github.com/OPSWAT/metadefender-gatling-test/files/6068970/logs5.txt)

**Comment by petya2164** [comment]
@cccs-kevin Your log shows that Java 11 manages to find the 32-bit version of netty_tcnative: 
```
08:28:48.998 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - Successfully loaded the library C:\Users\<user>\AppData\Local\Temp\netty_tcnative_windows_x86_6418011352597980945987.dll
08:28:48.999 [main] DEBUG io.netty.handler.ssl.OpenSsl - Initialize netty-tcnative using engine: 'default'
08:28:48.999 [main] DEBUG io.netty.handler.ssl.OpenSsl - netty-tcnative using native library: BoringSSL
```
I think this solves the missing libraries problem, therefore I will close this issue and we can continue debugging in the other issue that you raised.
